### ISSUE TITLE
Automatically updating minions.js

### ISSUE THREAD

**Issue by JimLiu0** [JimLiu0/bg-probabilities#71]
Thanks to @AndreC93, I now know about https://api.hearthstonejson.com/v1/latest/.

There might be some way to automatically update minions.js by 

1. Fetching minions from the API that have BG database id
2. Maintaining a list of removed cards and removing those minions from the file
3. Adding relevant fields like tribal synergy for cards like Nadina/Wrath weaver

**Comment by AndreC93** [comment]
For point 3, can probably look through the card text for tribe types and add any found tribe types to the synergy field.
