### ISSUE TITLE
Amalgadon and LightFang filtered

### ISSUE THREAD

**Issue by AndreC93** [JimLiu0/bg-probabilities#75]
The tribe filtering is always filtering out LightFang Enforcer and Amalgadon, since it only looks if something contains one of the missing tribes.

1. One option would be to change the tribe tag to be 'ALL' instead of being a joined string of all the tribes for lightfang/amal.
2. Another option would be to refactor the `App#changeBuyableCards` method. 

I think the first option makes more sense, but wanted to run it by you before throwing up a PR.

**Comment by JimLiu0** [comment]
I opted to go with the 2nd option so if dual or more tribal cards get added in the future, they can be handled properly. I made  #76 to handle this.
