### ISSUE TITLE
Clicking on "Calculate Probability" multiple times yields different probabilities

### ISSUE THREAD

**Issue by legrumsx** [JimLiu0/bg-probabilities#92]
How to reproduce (but it doesn't matter it seems):
Banned tribe 1: Beast
Banned tribe 2: Demon
Banned tribe 3: Dragon
Banned tribe 4: Mech

The current tavern is 2

at least  1  Deck Swabbie if  2  are missing  in  1  rolls

Click "Calculate Probability" multiple times: different result each time within a range.

**Comment by JimLiu0** [comment]
Hey Legrum, the application runs 100,000 simulations to arrive at a probability so the results will vary by a little as it is not an exact calculation.

**Comment by legrumsx** [comment]
Hi Jim
Thanks for the quick answer. I thought it would be based on probabilities formulas, I didn't check the code first, my bad.
